version: '3.4'

services:
  storemanager:
    image: ${DOCKER_REGISTRY-}storemanager
    build:
      context: .
      dockerfile: StoreManager/Dockerfile

  identityconfigurationsample:
    image: ${DOCKER_REGISTRY-}identityconfigurationsample
    build:
      context: .
      dockerfile: IdentityConfigurationSample/Dockerfile


  server.identity:
    image: ${DOCKER_REGISTRY-}serveridentity
    build:
      context: .
      dockerfile: identity/IdentityServer/Dockerfile

  mysql:
    image: mysql:8.0
    

